### ISSUE TITLE
level of maturity

### ISSUE THREAD

**Issue by 5axes** [fieldOfView/Cura-MeasureTool#1]
Is it already usable ?  nothing is shown or displayed in my case

**Comment by fieldOfView** [comment]
No, it isn't.

**Comment by fieldOfView** [comment]
At least now it shows the picked position in a minimal panel.

**Comment by 5axes** [comment]
ok
![Capture](https://user-images.githubusercontent.com/11015345/82688185-b7078580-9c58-11ea-9d50-94c356107e63.JPG)

**Comment by 5axes** [comment]
ok
![Capture](https://user-images.githubusercontent.com/11015345/82709487-fe097100-9c80-11ea-9bff-081c2c98a4f7.JPG)

**Comment by fieldOfView** [comment]
There is no need to keep sending me screenshots of this plugin ;-)
This is still a work in progress, and it will be a little while before it is a useful plugin.
