### ISSUE TITLE
[Question] Which measure units does the tool use? (i.e how does the measuring works?)

### ISSUE THREAD

**Issue by lihuelworks** [fieldOfView/Cura-MeasureTool#10]
Hi, first I wanted to say that I love the tool. Can't believe Cura doesn't have a simple tool to measure the size of a piece (reading about it on the first thread of the project, [I understand that is kind of difficult](https://github.com/fieldOfView/Cura-MeasureTool/issues/2#issuecomment-612032308)). Even so, I'd like to know if it's possible to have info on what unit is shown on the panel (maybe based on the 3D printer size, or any data that Cura might use to scale down to prints. For example, given this screenshot for this .stl from thingiverse [(link)](https://www.thingiverse.com/thing:4941382):

![image](https://user-images.githubusercontent.com/49965980/142420699-fa8995d1-dd9f-4e58-ae20-07b01cbb9671.png)

I'd like to know if the 40 is in mm, cm or inches, or if it's just a measure of scale and I need to calculate the numbers myself depending on the printer.

I'm pretty new to using Cura, sorry if I make any assumptions about the software.

**Comment by fieldOfView** [comment]
Like most sizes and distances in Cura, it is all in mm.

**Comment by lihuelworks** [comment]
Thanks! That's all thank you for working on the plugin 🙌🏽
