### ISSUE TITLE
How do I install it

### ISSUE THREAD

**Issue by pxUs3** [fieldOfView/Cura-MeasureTool#11]
Could you please add the instruction how to use it to read me

**Comment by RufusVS** [comment]
You can import it from the Marketplace.   I found this out.

**Comment by NG-Corp** [comment]
it isn't on marketplace

**Comment by fieldOfView** [comment]
Unfortunately, Ultimaker screwed up their Marketplace backend. The workaround is to log out of your account in Cura, and then use the Marketplace dialog in Cura to install the plugin. Finally you can decide if you want to log back in again.
