### ISSUE TITLE
Shouldn't the README.md contain installation instructions?

### ISSUE THREAD

**Issue by RufusVS** [fieldOfView/Cura-MeasureTool#12]
This looks like a very convenient plugin, but there are no instructions for a Cura noob like me on how a person would install it.

**Comment by RufusVS** [comment]
I found out it can be imported from the Marketplace in Cura.  I don't think the README.md mentioned that...

**Comment by RufusVS** [comment]
If it is available from the marketplace button within Cura, that should be mentioned in the Readme File.  Ready or not, it will avoid issues like mine (which I saw there were a half dozen or so).  I'll close this but I hope others with this question find my answer until the readme is modified.

**Comment by fieldOfView** [comment]
Cura plugins are available in the Marketplace, that's how it works. I don't think this should have to be mentioned in every plugin readme.
