### ISSUE TITLE
Cura 5.0 with Dark Theme

### ISSUE THREAD

**Issue by 5axes** [fieldOfView/Cura-MeasureTool#15]
Not a big issue, but just to improve the user interface .If you are using a Dark Theme , in such configuration the toolbar icon is not very visible.

![image](https://user-images.githubusercontent.com/11015345/166505372-713012be-1f60-4824-9385-51b0bf74ad99.png)

**Comment by fieldOfView** [comment]
I have fixed in master already. Thanks for reporting though.
