### ISSUE TITLE
Attribute check ShiftModifier 

### ISSUE THREAD

**Issue by jellespijker** [fieldOfView/Cura-MeasureTool#18]
I noticed during the plugin review for the SDK 8.0 upgrade that you use a try and catch block, isn't it more efficient to check with a `hasattr` check. You could also consider moving the check out of the event function completely. Since this is only done for the for pyqt6 switch

https://github.com/fieldOfView/Cura-MeasureTool/blob/d57aafebcb9ce2ec5c0b2ae8082c691042449352/MeasureTool.py#L196

**Comment by fieldOfView** [comment]
I've been told that it is better to ask for forgiveness than to ask for permission (in Python). But is is certainly a better idea to ask for forgiveness only once. Thanks!

**Comment by jellespijker** [comment]
>  better to ask for forgiveness than to ask for permission
This holds for most things in life, not just Python ;-)
