### ISSUE TITLE
[V1.1.0] Dimension in Micron are not correct 

### ISSUE THREAD

**Issue by 5axes** [fieldOfView/Cura-MeasureTool#20]
When I use the micron as unit, the distance On the X axis is not correct , it's the value in cm and not in Micron.

![image](https://user-images.githubusercontent.com/11015345/167809103-41272101-283e-4c13-b5b4-5af78a200b6a.png)

**Comment by 5axes** [comment]
dEdit : Not only on X looks like to be the wrong value but only on the "Main direction" If I try to measure the cube 20x20 on the Z direction I have the same issue.
![image](https://user-images.githubusercontent.com/11015345/167810033-a7dc4653-665d-4e56-8401-e7a26da8c512.png)

**Comment by fieldOfView** [comment]
Ok, I'll have to remove the Micron option, since the way I use to measure is not accurate enough.

**Comment by fieldOfView** [comment]
Ah, I see, the panel is chopping off too many zeros.

**Comment by 5axes** [comment]
Old Issus solved .. can close it
