### ISSUE TITLE
Plugin Translation

### ISSUE THREAD

**Issue by 5axes** [fieldOfView/Cura-MeasureTool#24]
Hello,
I saw that you are now generating the .pot file for the plugin translation. Can we translate the .po file corresponding to the language and where to put the .mo file in the plugin directory?

Thanks in advance,

**Comment by fieldOfView** [comment]
See https://github.com/fieldOfView/Cura-OctoPrintPlugin/tree/master/i18n as an example. You should only have to add the .po, and a github action will create another PR to create the .mo. The .mo will be kept up to date when strings moved around etc (but obviously new strings will need an updated .po).
