### ISSUE TITLE
Disabled in Cura 4.4.1 on Ubuntu 18

### ISSUE THREAD

**Issue by jabberwo** [fieldOfView/Cura-MeasureTool#28]
In list of extensions its grayed out.  
![image](https://user-images.githubusercontent.com/20709535/215353405-30a6e7b1-f160-490c-94d9-75343d86225a.png)

**Comment by fieldOfView** [comment]
I'm going to need to see your Cura.log to know why the plugin is not loaded.

Are you using the AppImage provided by Ultimaker, or some other distribution? NB: Many unofficial distributions are missing dependencies, not just for this plugin but also for parts of Cura itself.

**Comment by fieldOfView** [comment]
I can't help you without the additional information I requested.
