### ISSUE TITLE
How to install it manually because i can't login from the software

### ISSUE THREAD

**Issue by microSoftware** [fieldOfView/Cura-MeasureTool#41]
I have this message when i click login from the software on macos. 
![Screen Shot 2024-07-01 at 10 32 41](https://github.com/fieldOfView/Cura-MeasureTool/assets/3915272/1d6a5484-efd8-4d8e-b9c6-b7fa66e28221)

It's natural it doesn't work because Cura desktop software is local (localhost), so when the callback from account.ultimaker.com call this localhost callback, it's not accessible. So the localhost callback cannot be fulfilled. 

Anyway, because i can't login with Cura. I can't install the plugin measuring tool. Is there a way to install it manually by copying this plugin in a folder ?

**Comment by microSoftware** [comment]
i just needed to disable firewall.

**Comment by microSoftware** [comment]
i just needed to disable firewall.

**Comment by fieldOfView** [comment]
You do not have to be logged in to use the Marketplace.

**Comment by microSoftware** [comment]
> You do not have to be logged in to use the Marketplace.

Yes, we do sadly. You cannot install plugins in Cura without being logged into your Cura account in the desktop version on macOS. I don't know about the windows version.

**Comment by fieldOfView** [comment]
I am never logged in to my Ultimaker account in Cura.. Granted, I don't use the macOS version of Cura, but there is no macOS-specific code in Cura that requires being logged in to install plugins. You only need it if you want to select the plugins on marketplace.ultimaker.com. But there's a Marketplace dialog right inside Cura that allows you to install plugins _without logging in_.

Havbing said all that, you can download the plugin from the [releases page](https://github.com/fieldOfView/Cura-MeasureTool/releases),  Get the .curapackage for your version of Cura. Then drop this .curapackage file onto the buildplate in Cura, as if you were opening a 3d model.

**Comment by microSoftware** [comment]
okay thanks good to know. Anyway I managed to log by disabling my firewall.

Le lun. 1 juil. 2024 à 15:12, Aldo Hoeben ***@***.***> a
écrit :
