### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by wneves** [fieldOfView/Cura-MeasureTool#5]
Hi. Please make a tutorial to understand how to install the plug-in.

**Comment by fieldOfView** [comment]
Duplicate of https://github.com/fieldOfView/Cura-MeasureTool/issues/3

In short: this plugin is a work in progress. Don't use it.

**Comment by fieldOfView** [comment]
A test version can now be found here:
https://community.ultimaker.com/topic/36573-measure-tool-plugin/?tab=comments#comment-286716
