### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by dwery** [fieldOfView/Cura-MeasureTool#6]
Despite multiple efforts, I was unable to install this plugin locally.
Tried in the right path, edited the packages.json manually, but was unable to fool Cura 4.8 in loading it :-/

**Comment by fieldOfView** [comment]
Duplicate of #3

In short: this plugin is a work in progress. Don't use it.

**Comment by fieldOfView** [comment]
A test version can now be found here:
https://community.ultimaker.com/topic/36573-measure-tool-plugin/?tab=comments#comment-286716

**Comment by dwery** [comment]
Thank you
