### ISSUE TITLE
Inpredictable point picked in Orthographic view

### ISSUE THREAD

**Issue by 5axes** [fieldOfView/Cura-MeasureTool#7]
Tested the last release, and only the second point can be changed.   The first point always stay at the same position.

**Comment by fieldOfView** [comment]
There is no "release" yet, so I don't know exactly what version you are testing. 

I have changed how you set the two points. When clicking the tool moves the closest of the two points to the cursor. This makes it much more logical to drag and fine-tune the points. If you want the old behavior, hold down the shift key to alternate between the two points instead. This is documented in the README.

**Comment by 5axes** [comment]
Ok so just say "When clicking the tool moves the closest of the two points to the cursor"   this behaviour doesn't work in the current master branch

**Comment by fieldOfView** [comment]
Thanks for the added video. Could you save a project so I can test with this model?

**Comment by 5axes** [comment]
Yes I can upload a sample part, but not sure it can help you because every example produce the same issue. It's also depend if you start to select an entity or none.

https://user-images.githubusercontent.com/11015345/116115052-48c61100-a6ba-11eb-9db2-698537a47b5b.mp4

Second video , Part are not select before to clic the first point.

https://user-images.githubusercontent.com/11015345/116115170-685d3980-a6ba-11eb-94c5-eed4e29ff0a9.mp4

 sample project 
[Cube_Base.zip](https://github.com/fieldOfView/Cura-MeasureTool/files/6378521/Cube_Base.zip)

**Comment by fieldOfView** [comment]
Weird. Are you sure you are on commit 909137ac04668b4df5f30e2bcbbd7909516592da with no local changes?

What happens when you load no models, and just measure the two points on the buildplate?
Does holding down the shift key while clicking at least restore the old behavior of alternating between from and to points?

**Comment by 5axes** [comment]
Yes, it must be the commit 909137a  (Current source code on the Github) 
Without Part , we have the same result .

https://user-images.githubusercontent.com/11015345/116122456-191b0700-a6c2-11eb-83cb-574fc56f5224.mp4

With the shift button it's OK

https://user-images.githubusercontent.com/11015345/116122582-4798e200-a6c2-11eb-94eb-dc8f9d8a5af7.mp4

**Comment by fieldOfView** [comment]
Ah, got it. The reason I could not reproduce this is that you use an orthographic view, and I was trying to reproduce this in perspective view.

**Comment by 5axes** [comment]
Yes, Not easy to find .. I can confirm , no issue in perspective view. Got the problem only in orthographic view !

**Comment by fieldOfView** [comment]
If only I had paid more attention in linear algebra class...

**Comment by fieldOfView** [comment]
Could you test if the latest master behaves at least a little more predictable?

**Comment by 5axes** [comment]
Still have some issues in orthographic view when one point is on the buildplate.

https://user-images.githubusercontent.com/11015345/116236082-e83cdf80-a75e-11eb-9fb3-9a0568f059db.mp4

**Comment by fieldOfView** [comment]
I think I've got it now. Not that I suddenly understand the matrix math behind it, but your "when one point is on the buildplate" remark gave me a hunch. https://github.com/fieldOfView/Cura-MeasureTool/commit/3ee0efa2e71c5bbd250aa08592051b8e901bd5b5

**Comment by 5axes** [comment]
Ok it works now  ! (even if I think this new behavior is not a very good idea)

**Comment by fieldOfView** [comment]
There's always the shift key.

**Comment by 5axes** [comment]
Yes I know but finaly it will (on my point of view) bring some confusion for the user. Who reads the manal first and especialy when it concern Cura Plugins ? And finaly we best way to use it will be to always use the shift key, So finaly you are going back to the orginal behaviour, With the Shift key as well.

**Comment by fieldOfView** [comment]
I really think the current way is superior to the original way.

The current way allows you to fine-tune the position you picked after releasing the mouse button. The current wat also allows you to measure different points from a single origin.

I'll revisit the way points are selected after the first version is available in the Marketplace. But I really think this is better than what I had before, and you may be biased now by the experience you had before. I may be wrong; time - and user feedback - will tell.
