### ISSUE TITLE
Linux installed but not there

### ISSUE THREAD

**Issue by wb7qvm** [fieldOfView/Cura-MeasureTool#9]
Problem with Cura Linux Mint installation. The Measuring tool does not appear in the left tool zone after install. The marketplace shows with a green check mark indicating that it is installed but a no show in Cura. It could be  I am missing something jn Linux because I just made the switch from Win 10 to Linux Mint OS.

**Comment by fieldOfView** [comment]
Please post a link to your Cura.log file, which can be found in ~/.local/share/cura/<Cura version>/cura.log

**Comment by wb7qvm** [comment]
forgot to post the log file (sorry)
[cura.log](https://gith
[cura.log](https://github.com/fieldOfView/Cura-MeasureTool/files/7148293/cura.log)
ub.com/fieldOfView/Cura-MeasureTool/files/7148291/cura.log)

**Comment by fieldOfView** [comment]
In short: Use the AppImage provided by Ultimaker, instead of whatever you use now.

Your system is missing a required dependency: trimesh. The AppImage provided by Ultimaker has all the dependencies you need.
